export const ROUTES = {
  SIGNUP: 'SignUp',
  LOGIN: 'Login',
  OTP: 'OtpVerification',
  MAIN_TABS: 'MainTabs',
  HOME: 'Home',
  FOR_YOU: 'ForYou',
  MEMBERSHIP: 'MembershipScreen',
  MY_LIST: 'MyList',
  MY_WALLET: 'MyWallet',
  TOP_UP: 'TopUp',
  TRANSACTION_HISTORY: 'TransactionHistory',
  EARN_REWARDS: 'EarnRewards',
  PROFILE: 'Profile',
  SHOW_PLAYER: 'ShowPlayer',
};
